// These puzzles take time to generate, so I've pre-generated some for the website. To see the code for the generator, sorter, and more puzzles, visit www.github.com/monkwire/cross_words.


const puzzles = [[['STUBS', 'CAROL', 'AMINO', 'RENEW', 'PRESS'], ['STUBS', 'RULER', 'UNCLE', 'CAROL', 'DEMUR', 'RENEW', 'AMINO', 'PRESS', 'CIRCA', 'WHIST']],[['SILKS', 'AMINO', 'RAVER', 'AGREE', 'NEEDS'], ['SILKS', 'AGREE', 'BREVE', 'NEEDS', 'CHEEK', 'RAVER', 'OFFER', 'ORBIT', 'ITCHY', 'AMINO']],[['SCAMS', 'TORAH', 'ALONE', 'NOSED', 'DRESS'], ['TORAH', 'TENET', 'GRINS', 'MAYOR', 'KINDS', 'SCAMS', 'NOSED', 'ALONE', 'OWNER', 'DRESS']],[['TRADE', 'RIMED', 'USING', 'SENSE', 'TREES'], ['LORES', 'SENSE', 'TREES', 'LEAKS', 'RIMED', 'SLEWS', 'MELBA', 'TRADE', 'ADOBE', 'USING']], [['ADMIT', 'MEANS', 'BUFFA', 'ICIER', 'TEARS'], ['ICIER', 'ADMIT', 'REEKY', 'LINKS', 'BUFFA', 'SHOES', 'MEANS', 'MANOR', 'APSES', 'TEARS']],[['SHARP', 'LANAI', 'ASIDE', 'STOAT', 'HENRY'], ['LANAI', 'FEVER', 'SPORE', 'BATES', 'ASIDE', 'HENRY', 'SHARP', 'RAILS', 'MERGE', 'STOAT']],[['GNASH', 'RIFLE', 'ICIER', 'THREE', 'SEEKS'], ['ICIER', 'SEEKS', 'RIFLE', 'THREE', 'EVILS', 'QUEUE', 'RIGHT', 'CLOCK', 'KENAF', 'GNASH']],[['TAUNT', 'RATIO', 'ERECT', 'AGREE', 'THIRD'], ['MANSE', 'RATIO', 'TAUNT', 'KLUNK', 'NATAL', 'OUTER', 'GRAVE', 'THIRD', 'AGREE', 'ERECT']],[['CASES', 'AGAPE', 'LITER', 'KLIEG', 'SENSE'], ['AGAPE', 'KLIEG', 'SENSE', 'RAPER', 'LITER', 'SCRAP', 'AUDIO', 'CASES', 'TOTES', 'RIGHT']],[['SMART', 'CATER', 'AROSE', 'TILES', 'SALTS'], ['CATER', 'SNOWY', 'HOSTS', 'MAYST', 'AROSE', 'MINDS', 'SMART', 'SALTS', 'WORSE', 'TILES']],[['BOWEL', 'ABASE', 'RECTA', 'BAKER', 'SHORN'], ['SHORN', 'EMPTY', 'ABASE', 'BANDS', 'VERBS', 'BOWEL', 'BAKER', 'RECTA', 'CARDS', 'KELLY']],[['ANENT', 'BOXER', 'UTERI', 'SERVE', 'ESTER'], ['ANENT', 'SPAWN', 'RULES', 'ESTER', 'SELLS', 'REPLY', 'BOXER', 'SERVE', 'UTERI', 'DOORS']],[['ACUTE', 'PETER', 'INTRA', 'STEMS', 'HORSE'], ['FUMED', 'ACUTE', 'STEMS', 'STEAL', 'HUMOR', 'HORSE', 'VOTED', 'DRUBS', 'PETER', 'INTRA']],[['SPOOL', 'CORGI', 'AWARE', 'METER', 'PRESS'], ['CORGI', 'AWARE', 'SPOOL', 'METER', 'DENIM', 'CRUEL', 'CARAT', 'SOUND', 'PRESS', 'PLAYS']]];


exports.get_random_puzzle = function() {
    return puzzles[Math.floor(Math.random() * puzzles.length)]
}
